### ISSUE TITLE
Dependency of Numix icon themes

### ISSUE THREAD

**Issue by jorgicio** [Spike-Pentesting/spike-overlay#25]
Hi! Thanks for providing the Numix icon set. However, something to keep in mind:
the Numix icon themes derivated from (circle, utouch), depends on numix-icon-theme. Without it, all icons cannot be viewed right. So please, add numix-icon-theme as dependency for numix-icon-theme-circle and numix-icon-theme-utouch.

Thanks.

**Comment by dgikiller** [comment]
@jorgicio thank you for your feedback. We already know that but we moved and fixed those packages in Sabayon upstream repositories, so soon this packages will be removed from this repository.
:beers:
